@echo off
echo [1/5] Initializing Git...
git init
echo [2/5] Adding remote...
git remote add origin https://github.com/chandanv1010/crm.git
echo [3/5] Adding all files (including vendor and node_modules)... This might take a moment...
git add .
echo [4/5] Committing changes...
git commit -m "Initial commit with vendor and node_modules"
git branch -M main
echo [5/5] Pushing to remote repository...
git push -f -u origin main
